module Crayon

  EMPTY_COMMENT = "# \n"
  BLOCK_COMMENT = "#\n# hello\n# goodbye\n#"
  COMMENT = "# Hello world!"
  VAR_ASSIGN = "set x to 10"
  EQUATION_ASSIGN = "set x to 1 + 2 + 3 + 4"
  ARRAY_ASSIGN = "set a to [1, 2, 3, 4, 5, 6, 7]"
  FUNC_RETURN_ASSIGN = "set result to random with min as 0, max as 100"
  SIMPLE_FUNC_CALL = "print y"
  SINGLE_LINE_FUNC_CALL = "draw \"circle\" with radius as 10, color as \"black\""
  MULTILINE_FUNC_CALL = "draw \"circle\" with\n\tradius as 10\n\tcolor as \"black\"\nend"
  FUNC_CALL_NO_DEFAULT = "draw_circle with center as [50, 50]"
  SIMPLE_LOOP = "repeat 10 times\nend"
  SIMPLE_COUNTER_LOOP = "repeat 10 times with i\nend"
  LOOP = "repeat i from 0 to 10\nend"
  WHILE_LOOP = "repeat while x < 10\nend"
  IF = "if x < 10\nend"
  INLINE_IF = "print \"hello\" if true"
  IF_ELSE = "if x ≥ y\nprint y\nelse\nprint x\nend"
  IF_ELSE_IF = "if x ≥ y\nprint y\nelse if x < y\nprint x\nend"
  IF_ELSE_IF_ELSE_IF = "if x > y\nprint x\nelse if x < y\nprint y\nelse if x = y\nprint 0\nend"
  UNLESS = "unless x < 10\nend"
  INLINE_UNLESS = "print \"hello\" unless true"
  OBJECT_PROPERTY = "print length of list"
  LIST_ITEM_NUMBER = "print item 5 of list"
  LIST_ITEM_VAR = "print item i of list"
  START_EVENT = "do my_function on frame"
  STOP_EVENT = "stop doing my_function on frame"

end
